<?php

namespace App\Modules\Distributor\Domain\Capabilities;

enum DistributorCapabilityCode: string
{
    case ACCOUNT_DISABLED = 'ACCOUNT_DISABLED';
    case PROFILE_NOT_ACTIVE = 'PROFILE_NOT_ACTIVE';
    case BRANCH_INACTIVE = 'BRANCH_INACTIVE';
    case COORDINATOR_REQUIRED = 'COORDINATOR_REQUIRED';
    case CATEGORY_REQUIRED = 'CATEGORY_REQUIRED';
    case CATEGORY_NOT_USABLE = 'CATEGORY_NOT_USABLE';
    case DELINQUENCY_BLOCK = 'DELINQUENCY_BLOCK';
    case CREDIT_VALIDATION_REQUIRED = 'CREDIT_VALIDATION_REQUIRED';
}
