<?php

return [
    'trusted_proxies' => env('TRUSTED_PROXIES'),
    'frontend_url' => env('FRONTEND_URL', 'http://localhost:4200'),
    'initial_manager' => [
        'enabled' => env('INITIAL_GENERAL_MANAGER_ENABLED', false),
        'name' => env('INITIAL_GENERAL_MANAGER_NAME'),
        'email' => env('INITIAL_GENERAL_MANAGER_EMAIL'),
    ],
    'required' => [
        'app_key' => env('APP_KEY'),
        'db_primary_host' => env('MARIADB_PRIMARY_HOST') ?: env('MARIADB_HOST'),
        'db_replica_host' => env('MARIADB_REPLICA_HOST') ?: env('MARIADB_PRIMARY_HOST') ?: env('MARIADB_HOST'),
        'db_database' => env('DB_DATABASE'),
        'db_primary_username' => env('DB_PRIMARY_USERNAME') ?: env('DB_USERNAME'),
        'db_primary_password' => env('DB_PRIMARY_PASSWORD') ?: env('DB_PASSWORD'),
        'db_replica_username' => env('DB_REPLICA_USERNAME') ?: env('DB_PRIMARY_USERNAME') ?: env('DB_USERNAME'),
        'db_replica_password' => env('DB_REPLICA_PASSWORD') ?: env('DB_PRIMARY_PASSWORD') ?: env('DB_PASSWORD'),
        'redis_host' => env('REDIS_HOST'),
        'redis_password' => env('REDIS_PASSWORD'),
        'reverb_app_id' => env('REVERB_APP_ID'),
        'reverb_app_key' => env('REVERB_APP_KEY'),
        'reverb_app_secret' => env('REVERB_APP_SECRET'),
        'reverb_host' => env('REVERB_HOST'),
        'storage_key' => env('AWS_ACCESS_KEY_ID'),
        'storage_secret' => env('AWS_SECRET_ACCESS_KEY'),
        'storage_bucket' => env('AWS_BUCKET'),
        'trusted_proxies' => env('TRUSTED_PROXIES'),
        'client_data_hmac_key' => env('CLIENT_DATA_HMAC_KEY'),
        'mail_host' => env('MAIL_HOST'),
        'mail_username' => env('MAIL_USERNAME'),
        'mail_password' => env('MAIL_PASSWORD'),
    ],
];
