<?php

declare(strict_types=1);

namespace App\Modules\Reporting\Domain\Enums;

enum ReportCode: string
{
    case DISTRIBUTORS_BY_BRANCH_COORDINATOR = 'DISTRIBUTORS_BY_BRANCH_COORDINATOR';
    case CREDIT_LINE_SUMMARY = 'CREDIT_LINE_SUMMARY';
    case VOUCHERS_BY_STATUS = 'VOUCHERS_BY_STATUS';
    case RELATIONS_BY_CUT = 'RELATIONS_BY_CUT';
    case RELATION_BALANCES = 'RELATION_BALANCES';
    case DISTRIBUTOR_PAYMENT_CLASSIFICATION = 'DISTRIBUTOR_PAYMENT_CLASSIFICATION';
    case DELINQUENT_DISTRIBUTORS = 'DELINQUENT_DISTRIBUTORS';
    case CLIENT_INFORMATIONAL_PORTFOLIO = 'CLIENT_INFORMATIONAL_PORTFOLIO';
    case RISK_ALERT_CONSECUTIVE_RELATIONS = 'RISK_ALERT_CONSECUTIVE_RELATIONS';
    case RECONCILED_PAYMENTS = 'RECONCILED_PAYMENTS';
    case UNRECONCILED_PAYMENTS = 'UNRECONCILED_PAYMENTS';
    case MANUAL_RECONCILIATIONS = 'MANUAL_RECONCILIATIONS';
    case PENDING_EXCESSES = 'PENDING_EXCESSES';
    case CREDIT_BALANCES_AND_APPLICATIONS = 'CREDIT_BALANCES_AND_APPLICATIONS';
    case REFUNDS_BY_STATUS = 'REFUNDS_BY_STATUS';
    case DISTRIBUTOR_POINTS_BALANCE = 'DISTRIBUTOR_POINTS_BALANCE';
    case POINT_MOVEMENTS = 'POINT_MOVEMENTS';
    case DISTRIBUTOR_APPLICATIONS_BY_RESULT = 'DISTRIBUTOR_APPLICATIONS_BY_RESULT';
    case CREDIT_INCREASES_BY_STATUS = 'CREDIT_INCREASES_BY_STATUS';
    case CLIENT_TRANSFERS_AND_REASSIGNMENTS = 'CLIENT_TRANSFERS_AND_REASSIGNMENTS';
    case BRANCH_AND_COORDINATOR_CHANGES = 'BRANCH_AND_COORDINATOR_CHANGES';
}
