<?php

namespace App\Enums;

enum ApplicationStatus: string
{
    case DRAFT = 'DRAFT';
    case COORDINATOR_REVIEW = 'COORDINATOR_REVIEW';
    case VERIFIER_ASSIGNED = 'VERIFIER_ASSIGNED';
    case PHYSICAL_VERIFICATION = 'PHYSICAL_VERIFICATION';
    case COORDINATOR_CORRECTION = 'COORDINATOR_CORRECTION';
    case COORDINATOR_EVALUATION = 'COORDINATOR_EVALUATION';
    case MANAGER_AUTHORIZATION = 'MANAGER_AUTHORIZATION';
    case TERMINATED_UNFAVORABLE = 'TERMINATED_UNFAVORABLE';
    case REJECTED = 'REJECTED';
    case AUTHORIZED_PENDING_ACTIVATION = 'AUTHORIZED_PENDING_ACTIVATION';
    case ACTIVE = 'ACTIVE';
}
