<?php

namespace App\Enums;

enum CodigoErrorDistribuidora: string
{
    case SOLICITUD_NO_APROBADA = 'DISTRIBUTOR_APPLICATION_NOT_APPROVED';
    case YA_EXISTE = 'DISTRIBUTOR_ALREADY_EXISTS';
    case CONFLICTO_NUMERO = 'DISTRIBUTOR_NUMBER_CONFLICT';
    case CATEGORIA_NO_PUBLICADA = 'DISTRIBUTOR_CATEGORY_NOT_PUBLISHED';
    case CATEGORIA_NO_VIGENTE = 'DISTRIBUTOR_CATEGORY_NOT_EFFECTIVE';
    case ALCANCE_COORDINADOR_INVALIDO = 'DISTRIBUTOR_COORDINATOR_SCOPE_INVALID';
    case SUCURSAL_NO_COINCIDE = 'DISTRIBUTOR_BRANCH_MISMATCH';
    case CONFLICTO_USUARIO = 'DISTRIBUTOR_USER_CONFLICT';
    case LINEA_INICIAL_INVALIDA = 'DISTRIBUTOR_INITIAL_CREDIT_INVALID';
    case ESTADO_ACTIVACION_INVALIDO = 'DISTRIBUTOR_ACTIVATION_STATE_INVALID';
    case LIMITE_REENVIO = 'DISTRIBUTOR_INVITATION_RATE_LIMITED';
    case CONFLICTO_VERSION = 'RESOURCE_VERSION_CONFLICT';
    case ALCANCE_DENEGADO = 'AUTH_SCOPE_DENIED';
}
