<?php

namespace App\Enums;

enum CodigoErrorSolicitudDistribuidora: string
{
    case NO_ENCONTRADA = 'DISTRIBUTOR_APPLICATION_NOT_FOUND';
    case NO_EDITABLE = 'DISTRIBUTOR_APPLICATION_NOT_EDITABLE';
    case INCOMPLETA = 'DISTRIBUTOR_APPLICATION_INCOMPLETE';
    case YA_ENVIADA = 'DISTRIBUTOR_APPLICATION_ALREADY_SUBMITTED';
    case SUCURSAL_INVALIDA = 'DISTRIBUTOR_APPLICATION_BRANCH_INVALID';
    case COORDINADOR_INVALIDO = 'DISTRIBUTOR_APPLICATION_COORDINATOR_INVALID';
    case SECCION_INCOMPLETA = 'DISTRIBUTOR_APPLICATION_SECTION_INCOMPLETE';
    case SECCION_NO_APLICABLE = 'DISTRIBUTOR_APPLICATION_SECTION_NOT_APPLICABLE';
    case DOMICILIO_ACTUAL_REQUERIDO = 'DISTRIBUTOR_APPLICATION_CURRENT_RESIDENCE_REQUIRED';
    case DOMICILIO_ACTUAL_DUPLICADO = 'DISTRIBUTOR_APPLICATION_CURRENT_RESIDENCE_DUPLICATE';
    case REGISTRO_HIJO_NO_ENCONTRADO = 'DISTRIBUTOR_APPLICATION_CHILD_NOT_FOUND';
    case TRANSICION_INVALIDA = 'DISTRIBUTOR_APPLICATION_INVALID_TRANSITION';
    case DATOS_SENSIBLES_INVALIDOS = 'DISTRIBUTOR_APPLICATION_SENSITIVE_DATA_INVALID';
    case CONFLICTO_VERSION = 'RESOURCE_VERSION_CONFLICT';
    case ALCANCE_DENEGADO = 'AUTH_SCOPE_DENIED';
}
