<?php

namespace App\Enums;

enum EstadoSolicitudDistribuidora: string
{
    case BORRADOR = 'DRAFT';
    case REVISION_COORDINADOR = 'COORDINATOR_REVIEW';
    case VERIFICADOR_ASIGNADO = 'VERIFIER_ASSIGNED';
    case VERIFICACION_FISICA = 'PHYSICAL_VERIFICATION';
    case CORRECCION_COORDINADOR = 'COORDINATOR_CORRECTION';
    case EVALUACION_COORDINADOR = 'COORDINATOR_EVALUATION';
    case AUTORIZACION_GERENCIAL = 'MANAGER_AUTHORIZATION';
    case TERMINADA_DESFAVORABLE = 'TERMINATED_UNFAVORABLE';
    case RECHAZADA = 'REJECTED';
    case AUTORIZADA_PENDIENTE_ACTIVACION = 'AUTHORIZED_PENDING_ACTIVATION';
    case ACTIVA = 'ACTIVE';
}
