<?php
namespace App\Enums;

enum MediaFileType: string {
    case RESIDENCE_EXTERIOR = 'RESIDENCE_EXTERIOR';
    case RESIDENCE_INTERIOR = 'RESIDENCE_INTERIOR';
    case IDENTIFICATION_EVIDENCE = 'IDENTIFICATION_EVIDENCE';
    case VEHICLE_EVIDENCE = 'VEHICLE_EVIDENCE';
    case ASSET_EVIDENCE = 'ASSET_EVIDENCE';
    case COMMERCIAL_EVIDENCE = 'COMMERCIAL_EVIDENCE';
    case OTHER = 'OTHER';
}
