<?php

namespace App\Enums;

enum TipoMovimientoLineaCredito: string
{
    case AUTORIZACION_INICIAL = 'INITIAL_AUTHORIZATION';
    case INCREASE = 'INCREASE';
    case VOUCHER_ISSUED = 'VOUCHER_ISSUED';
    case VOUCHER_CANCELLED = 'VOUCHER_CANCELLED';
    case VOUCHER_CASHED = 'VOUCHER_CASHED';
    case PAYMENT_RECOVERY = 'PAYMENT_RECOVERY';
}
