<?php

namespace App\Modules\Organization\Domain\Events;

enum OrganizationEventType: string
{
    case BRANCH_CREATED = 'BRANCH_CREATED';
    case BRANCH_UPDATED = 'BRANCH_UPDATED';
    case BRANCH_ACTIVATED = 'BRANCH_ACTIVATED';
    case BRANCH_DEACTIVATED = 'BRANCH_DEACTIVATED';
    case PERSONNEL_ASSIGNED = 'PERSONNEL_ASSIGNED';
    case PERSONNEL_REASSIGNED = 'PERSONNEL_REASSIGNED';
    case ASSIGNMENT_UPDATED = 'ASSIGNMENT_UPDATED';
    case ASSIGNMENT_ENDED = 'ASSIGNMENT_ENDED';
    case ORGANIZATION_SCOPE_DENIED = 'ORGANIZATION_SCOPE_DENIED';
}
