<?php

declare(strict_types=1);

namespace App\Modules\Reporting\Domain\Definitions;

use App\Modules\Access\Domain\Authorization\RoleCode;
use App\Modules\Reporting\Domain\Enums\ReportCode;
use App\Modules\Reporting\Domain\ValueObjects\ReportDefinition;

/**
 * Closed, versioned M16 catalog. Physical tables and columns are intentionally absent.
 */
final class OfficialReportDefinitions
{
    /** @return list<ReportDefinition> */
    public function all(): array
    {
        $internal = [
            RoleCode::GENERAL_MANAGER,
            RoleCode::SUCURSAL_MANAGER,
            RoleCode::COORDINATOR,
            RoleCode::ADMINISTRATOR,
        ];
        $withDistributor = [...$internal, RoleCode::DISTRIBUTOR];
        $commonScope = ['branch_id', 'coordinator_id', 'distributor_id'];
        $dates = ['date_from', 'date_to'];

        return [
            $this->definition(
                ReportCode::DISTRIBUTORS_BY_BRANCH_COORDINATOR,
                'Distribuidoras por sucursal y coordinador',
                'Asignación vigente de distribuidoras agrupada por sucursal y coordinador.',
                $internal,
                ['M02', 'M05'],
                [...$commonScope, 'status', 'category_id'],
                ['registered_at', 'status', 'distributor'],
                ['distributor', 'branch', 'coordinator', 'category', 'status', 'registered_at'],
                ['branch', 'coordinator', 'status'],
                ['distributors_total', 'by_branch', 'by_coordinator', 'by_status'],
            ),
            $this->definition(
                ReportCode::CREDIT_LINE_SUMMARY,
                'Resumen de línea de crédito',
                'Línea vigente y recuperación confirmada por M07.',
                $withDistributor,
                ['M07'],
                [...$commonScope, ...$dates, 'status'],
                ['distributor', 'available', 'updated_at'],
                ['distributor', 'total', 'used', 'available', 'recovered', 'status', 'restriction', 'last_authorized_increase'],
                ['branch', 'coordinator', 'status'],
                ['total', 'used', 'available', 'recovered_in_period'],
            ),
            $this->definition(
                ReportCode::VOUCHERS_BY_STATUS,
                'Prevales y vales por estado',
                'Prevales y vales digitales con sus valores históricos.',
                $withDistributor,
                ['M08', 'M09'],
                [...$commonScope, ...$dates, 'status', 'voucher_type', 'product_id', 'category_id', 'folio'],
                ['created_at', 'folio', 'status', 'capital'],
                ['folio', 'type', 'status', 'distributor', 'client', 'product_version', 'capital', 'created_at', 'holiday_at', 'historical_branch'],
                ['type', 'status', 'branch'],
                ['count', 'capital'],
                ['client'],
            ),
            $this->definition(
                ReportCode::RELATIONS_BY_CUT,
                'Relaciones por corte',
                'Relaciones definitivas y sus importes congelados por corte.',
                $withDistributor,
                ['M10'],
                [...$commonScope, ...$dates, 'status', 'cut_id', 'relation_id', 'reference'],
                ['cut', 'due_date', 'status', 'pending_balance'],
                ['cut', 'period', 'due_date', 'distributor', 'payment_reference', 'status', 'portfolio_total', 'misvales_due_total', 'pending_balance', 'surcharge', 'temporary_classification'],
                ['cut', 'status'],
                ['portfolio_total', 'misvales_due_total', 'pending_balance'],
                ['payment_reference'],
            ),
            $this->definition(
                ReportCode::RELATION_BALANCES,
                'Saldo de relaciones',
                'Componentes definitivos del saldo de cada relación.',
                $withDistributor,
                ['M10', 'M11', 'M12'],
                [...$commonScope, ...$dates, 'status', 'cut_id', 'relation_id', 'reference'],
                ['due_date', 'pending_balance', 'relation'],
                ['relation', 'distributor', 'original_balance', 'applied_amount', 'pending_balance', 'pending_capital', 'pending_financial_components', 'excess', 'credit_balance_applied'],
                ['status', 'cut'],
                ['original_balance', 'applied_amount', 'pending_balance', 'pending_capital', 'pending_financial_components'],
                ['reference'],
            ),
            $this->definition(
                ReportCode::DISTRIBUTOR_PAYMENT_CLASSIFICATION,
                'Clasificación de pago de distribuidoras',
                'Clasificación definitiva persistida por M11.',
                $withDistributor,
                ['M10', 'M11'],
                [...$commonScope, ...$dates, 'cut_id', 'payment_classification'],
                ['classification', 'distributor', 'cut'],
                ['distributor', 'cut', 'classification', 'classified_at'],
                ['classification', 'cut'],
                ['distributors_total', 'by_classification'],
            ),
            $this->definition(
                ReportCode::DELINQUENT_DISTRIBUTORS,
                'Distribuidoras morosas',
                'Morosidad aplicada, regularización y retiro sin inferir decisiones.',
                $internal,
                ['M14', 'M10'],
                [...$commonScope, ...$dates, 'status'],
                ['applied_at', 'overdue_balance', 'distributor'],
                ['distributor', 'branch', 'coordinator', 'delinquency_status', 'applied_at', 'deciding_manager', 'overdue_balance', 'regularization_status', 'active_removal_request'],
                ['branch', 'status'],
                ['distributors_total', 'overdue_balance'],
                ['deciding_manager'],
            ),
            $this->definition(
                ReportCode::CLIENT_INFORMATIONAL_PORTFOLIO,
                'Cartera informativa de clientes',
                'Cartera opcional e informativa, independiente de conciliación y morosidad.',
                $withDistributor,
                ['M06'],
                [...$commonScope, ...$dates, 'status'],
                ['updated_at', 'client', 'informational_balance'],
                ['client', 'distributor', 'vouchers', 'voucher_amounts', 'informational_balance', 'informational_status', 'reported_payments', 'last_reported_payment_at', 'updated_at'],
                ['status'],
                ['clients_total', 'informational_balance'],
                ['client'],
            ),
            $this->definition(
                ReportCode::RISK_ALERT_CONSECUTIVE_RELATIONS,
                'Alertas por relaciones consecutivas',
                'Tres relaciones exactas de una alerta de riesgo.',
                $internal,
                ['M14'],
                [...$commonScope, ...$dates, 'status', 'relation_id'],
                ['detected_at', 'status', 'distributor'],
                ['alert', 'distributor', 'relations', 'cuts', 'post_due_balances', 'relation_statuses', 'detected_at', 'responsible', 'status'],
                ['status', 'branch'],
                ['alerts_total'],
                ['responsible'],
            ),
            $this->definition(
                ReportCode::RECONCILED_PAYMENTS,
                'Pagos conciliados',
                'Movimientos bancarios conciliados sin duplicar aplicaciones.',
                $withDistributor,
                ['M11'],
                [...$commonScope, ...$dates, 'relation_id', 'folio', 'reference', 'conciliation_type'],
                ['bank_date', 'reconciled_at', 'received_amount', 'applied_amount'],
                ['bank_folio', 'reference', 'bank_date', 'reconciled_at', 'received_amount', 'applied_amount', 'relation', 'distributor', 'application_type', 'result'],
                ['application_type', 'result'],
                ['received_amount', 'applied_amount', 'payments_total'],
                ['bank_folio', 'reference'],
            ),
            $this->definition(
                ReportCode::UNRECONCILED_PAYMENTS,
                'Pagos no conciliados',
                'Movimientos bancarios pendientes o rechazados, nunca mostrados como aplicados.',
                $internal,
                ['M11'],
                [...$commonScope, ...$dates, 'status', 'folio', 'reference'],
                ['bank_date', 'amount', 'status'],
                ['bank_folio', 'received_reference', 'amount', 'bank_date', 'unreconciled_reason', 'status', 'clarification'],
                ['status', 'reason'],
                ['payments_total', 'amount'],
                ['bank_folio', 'received_reference'],
            ),
            $this->definition(
                ReportCode::MANUAL_RECONCILIATIONS,
                'Conciliaciones manuales',
                'Trazabilidad de solicitud, autorización y ejecución separadas.',
                [RoleCode::GENERAL_MANAGER, RoleCode::SUCURSAL_MANAGER, RoleCode::ADMINISTRATOR],
                ['M11'],
                [...$commonScope, ...$dates, 'status', 'relation_id', 'folio'],
                ['requested_at', 'status', 'applied_amount'],
                ['request', 'bank_movement', 'relation', 'reason', 'requester', 'authorizer', 'executor', 'dates', 'status', 'applied_amount'],
                ['status'],
                ['requests_total', 'applied_amount'],
                ['bank_movement', 'requester', 'authorizer', 'executor'],
            ),
            $this->definition(
                ReportCode::PENDING_EXCESSES,
                'Excedentes pendientes',
                'Excedentes todavía pendientes de una decisión en M12.',
                $withDistributor,
                ['M12'],
                [...$commonScope, ...$dates, 'status'],
                ['created_at', 'pending_amount'],
                ['excess', 'distributor', 'origin_payment', 'settled_relation', 'original_amount', 'pending_amount', 'created_at', 'status'],
                ['status'],
                ['excesses_total', 'original_amount', 'pending_amount'],
            ),
            $this->definition(
                ReportCode::CREDIT_BALANCES_AND_APPLICATIONS,
                'Saldos a favor y aplicaciones',
                'Saldo a favor definitivo y sus aplicaciones históricas.',
                $withDistributor,
                ['M12'],
                [...$commonScope, ...$dates, 'relation_id', 'status'],
                ['created_at', 'available', 'applied_total'],
                ['credit_balance', 'distributor', 'original', 'available', 'applied_total', 'applications', 'destination_relation', 'applied_at', 'remainder'],
                ['status'],
                ['original', 'available', 'applied_total'],
            ),
            $this->definition(
                ReportCode::REFUNDS_BY_STATUS,
                'Devoluciones por estado',
                'Solicitudes de devolución sin confundir autorización con finalización.',
                $withDistributor,
                ['M12'],
                [...$commonScope, ...$dates, 'refund_status'],
                ['requested_at', 'status', 'amount'],
                ['request', 'distributor', 'origin_excess', 'amount', 'status', 'requester', 'authority', 'executor', 'dates', 'reason'],
                ['status'],
                ['refunds_total', 'amount'],
                ['requester', 'authority', 'executor'],
            ),
            $this->definition(
                ReportCode::DISTRIBUTOR_POINTS_BALANCE,
                'Saldo de puntos por distribuidora',
                'Saldo total, disponible y reservado persistido por M13.',
                $withDistributor,
                ['M13'],
                $commonScope,
                ['updated_at', 'available_points', 'distributor'],
                ['distributor', 'total_points', 'available_points', 'reserved_points', 'current_value', 'updated_at'],
                ['branch', 'coordinator'],
                ['total_points', 'available_points', 'reserved_points'],
            ),
            $this->definition(
                ReportCode::POINT_MOVEMENTS,
                'Movimientos de puntos',
                'Movimientos definitivos de generación, descuento, reserva, liberación y canje.',
                $withDistributor,
                ['M13'],
                [...$commonScope, ...$dates, 'point_movement_type', 'relation_id'],
                ['effective_at', 'points', 'movement_type'],
                ['movement', 'distributor', 'movement_type', 'points', 'relation', 'effective_at', 'balance_after'],
                ['movement_type'],
                ['points_by_type'],
            ),
            $this->definition(
                ReportCode::DISTRIBUTOR_APPLICATIONS_BY_RESULT,
                'Solicitudes de distribuidora por resultado',
                'Solicitudes pendientes, favorables y desfavorables de M05.',
                $internal,
                ['M05'],
                [...$commonScope, ...$dates, 'status', 'application_result', 'folio'],
                ['created_at', 'folio', 'status'],
                ['folio', 'branch', 'coordinator', 'status', 'review_result', 'verification_result', 'final_decision', 'dates'],
                ['application_result', 'status'],
                ['applications_total', 'by_result'],
            ),
            $this->definition(
                ReportCode::CREDIT_INCREASES_BY_STATUS,
                'Incrementos de crédito por estado',
                'Solicitudes e importes decididos de incrementos de línea.',
                $internal,
                ['M07'],
                [...$commonScope, ...$dates, 'increase_status'],
                ['requested_at', 'status', 'authorized_amount'],
                ['request', 'distributor', 'previous_line', 'requested_amount', 'preauthorized_amount', 'authorized_amount', 'result', 'coordinator', 'manager', 'dates'],
                ['status', 'result'],
                ['requested_amount', 'authorized_amount', 'requests_total'],
                ['manager'],
            ),
            $this->definition(
                ReportCode::CLIENT_TRANSFERS_AND_REASSIGNMENTS,
                'Transferencias y reasignaciones',
                'Procesos de movilidad conservando origen, destino y actores históricos.',
                $withDistributor,
                ['M15'],
                [...$commonScope, ...$dates, 'status', 'mobility_type', 'folio'],
                ['started_at', 'completed_at', 'status', 'folio'],
                ['folio', 'process_type', 'client', 'origin_distributor', 'destination_distributor', 'branch', 'status', 'actors', 'started_at', 'completed_at', 'reason'],
                ['process_type', 'status'],
                ['processes_total', 'completed_total'],
                ['client', 'actors'],
            ),
            $this->definition(
                ReportCode::BRANCH_AND_COORDINATOR_CHANGES,
                'Cambios de sucursal y coordinador',
                'Cambios administrativos y cobertura de lotes de coordinador.',
                $internal,
                ['M15'],
                [...$commonScope, ...$dates, 'status', 'mobility_type'],
                ['completed_at', 'status', 'distributor'],
                ['change_type', 'distributor', 'origin_branch', 'destination_branch', 'outgoing_coordinator', 'destination_coordinators', 'batch_total', 'reassigned_total', 'pending_clients', 'authority', 'status', 'dates'],
                ['change_type', 'status', 'branch'],
                ['changes_total', 'batch_total', 'reassigned_total'],
                ['authority'],
            ),
        ];
    }

    /**
     * @param  list<RoleCode>  $roles
     * @param  list<string>  $sources
     * @param  list<string>  $filters
     * @param  list<string>  $sort
     * @param  list<string>  $columns
     * @param  list<string>  $groups
     * @param  list<string>  $totals
     * @param  list<string>  $sensitive
     */
    private function definition(
        ReportCode $code,
        string $name,
        string $description,
        array $roles,
        array $sources,
        array $filters,
        array $sort,
        array $columns,
        array $groups,
        array $totals,
        array $sensitive = [],
    ): ReportDefinition {
        return new ReportDefinition(
            $code,
            $name,
            $description,
            $roles,
            $sources,
            array_values(array_unique($filters)),
            $sort,
            $columns,
            $groups,
            $totals,
            $sensitive,
        );
    }
}
